spring.application.name=identity-service

# Puerto del microservicio
server.port=8002

# Conexión a la Base de Datos (Ajustado a los valores estándar de tu Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=user_inv
spring.datasource.password=password_inv
spring.datasource.driver-class-name=org.postgresql.Driver

# ¡LA SOLUCIÓN! Cambiamos 'none' por 'update'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect