spring.application.name=identity-service

server.port=8002

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=user_inv
spring.datasource.password=password_inv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true